### ISSUE TITLE
Bug parsing some files

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/jeolconverter#4]
Trying to drag / drop the following file in NMRium:

[test.jdf.zip](https://github.com/cheminfo/jeolconverter/files/7072066/test.jdf.zip)

I obtain the following error that seems to be related to the jeol parser:

![image](https://user-images.githubusercontent.com/1484241/131241852-cb97b1c6-8761-4d8e-b082-ee173e3a0ece.png)

@jobo322 Could you try to solve this problem ?

**Comment by jobo322** [comment]
It was fixed in the new version
